### ISSUE TITLE
No MP4 file

### ISSUE THREAD

**Issue by anton-haxor** [ruess/bbb-download#3]
Hi

I have followed the steps but it isn't producing a MP4 file

Can I send you the log to see what is wrong?

**Comment by anton-haxor** [comment]
Sorry I found it

**Comment by Romerski** [comment]
@anton-haxor How did you do? I installed this script without errors but when I record a meeting and going through **https://yourBBBserverURL/download/presentation/{meetingID}/{meetingID}.mp4** I can only see webcam video but no presentation neither screenshare.

Thanks.
