### ISSUE TITLE
No final MP4

### ISSUE THREAD

**Issue by anton-haxor** [ruess/bbb-download#4]
Hi

It doesn't produce a MP4 with the components you mention

Can I send you the log file?

**Comment by Romerski** [comment]
@anton-haxor How did you do? I installed this script without errors but when I record a meeting and going through https://yourBBBserverURL/download/presentation/{meetingID}/{meetingID}.mp4 I can only see webcam video but no presentation neither screenshare.

Thanks.

**Comment by anton-haxor** [comment]
Hi Romerski

I only get  MP4 files in the directory: /var/bigbluebutton/unpublished/presentation/

**Comment by Romerski** [comment]
@anton-haxor Thanks for your response. Unluckily that directory is empty :( I get .mp4 file on previus URL I posted but only with webcam.

Did you do something more when installing script? I only run install.sh script as root without any errors.

**Comment by anton-haxor** [comment]
No nothing more

The install script worked 100%

**Comment by Romerski** [comment]
@anton-haxor And yo create a new conference, start recording and you get .mp4 file with screenshare and webcam o what do you get on that .mp4 video?

**Comment by anton-haxor** [comment]
No I only got the video even though I started a new conference with screen sharing

**Comment by Romerski** [comment]
Do you mean you only get webcam recording? No screenshare, no presentation? Because webcam can be download without any 3rd party script.

In the README it says "Final MP4 video will include only presentation, audio and screenshare".

**Comment by anton-haxor** [comment]
That is correct. I do not get: Screen share or presentation

The only MP4 output I get is the Webcam in the folder: /var/bigbluebutton/unpublished/presentation/

And nothing (Not even Webcam) in:  https://yourBBBserverURL/download/presentation/{meetingID}/{meetingID}.mp4

**Comment by Romerski** [comment]
So then this script is not working at all. It says: "Final MP4 video will include only presentation, audio and screenshare (no chat window, no whiteboard)."

And we are only getting webcam, which can be downloaded by default without the need of the script :(

Any help @ruess ? Thanks.

**Comment by ruess** [comment]
I didn't realize that the readme promised the presentation in the video. I'll make sure to update the read me in order to fix that. 

Our company not only did not need the presentation as a part of the mp4, but we intentionally did not want it in there. If all you're looking for is a way to generate the MP4, and you don't need the youtube upload functionality, I wouldn't even bother using our fork of the script. Feel free to just go to the original repository, and start from there!

**Comment by anton-haxor** [comment]
Thanks @ruess
